### ISSUE TITLE
choosenim devel --latest fails

### ISSUE THREAD

**Issue by bung87** [jiro4989/setup-nim-action#48]
```
 with:
29
    nim-version: devel --latest
30
    no-color: false
31
    yes: false
32
choosenim-init: Downloading choosenim-0.7.4_linux_amd64
33
Downloading Nim 1.4.8 from nim-lang.org
34
[                                                  ] 0.03814% 4kb/s[##################################################] 100.0% 0kb/s
35
 Extracting nim-1.4.8-linux_x64.tar.xz
36
   Building Nim 1.4.8
37
  Compiler: Already built
38
     Tools: Already built
39
  Installed component 'nim'
40
  Installed component 'nimble'
41
  Installed component 'nimgrep'
42
  Installed component 'nimpretty'
17
  Installed component 'nimsuggest'
18
  Installed component 'testament'
19
  Installed component 'nim-gdb'
20
   Switched to Nim 1.4.8
21
choosenim-init: ChooseNim installed in /home/runner/.nimble/bin
22
choosenim-init: You must now ensure that the Nimble bin dir is in your PATH.
23
choosenim-init: Place the following line in the ~/.profile or ~/.bashrc file.
24
choosenim-init:     export PATH=/home/runner/.nimble/bin:$PATH
25

26
Error: Error: Command failed: choosenim devel --latest 
27

28
/home/runner/work/_actions/jiro4989/setup-nim-action/v1/lib/installer.js:123
29
                    throw err;
30
                    ^
31

32
Error: Command failed: choosenim devel --latest 
33

34
    at ChildProcess.exithandler (child_process.js:295:12)
35
    at ChildProcess.emit (events.js:210:5)
36
    at maybeClose (internal/child_process.js:1021:16)
37
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
38
  killed: false,
39
  code: 1,
40
  signal: null,
41
  cmd: 'choosenim devel --latest '
42
}
```

**Comment by jiro4989** [comment]
I ran GitHub Actions below.

```yaml
      - run: |
          curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
          chmod +x ./init.sh
          ./init.sh -y
          export PATH=$PATH:$HOME/.nimble/bin
          choosenim --version
          choosenim devel --latest
```

The result is here. An error has occured.

https://github.com/jiro4989/setup-nim-action/runs/2808576135?check_suite_focus=true#step:3:49

I think the reason of errors is nim compiler of devel branches, or choosenim.
